version: 2
updates:
  # Configuration for Dockerfile
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:55"
      timezone: "Africa/Lagos"

