version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
       time: "12:20"
       timezone:: "Africa/Lagos"
