version: 2
updates:
  # Configuration for Dockerfile
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:55"
      timezone: "Africa/Lagos"

version: 2
updates:
  # Configuration for Dockerfile
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:00"
      timezone: "Africa/Lagos"

