name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: step 1
      id: random-number-generator
      env:
        STEP_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
      shell: bash
    - name: step 2
      id: random-number
     env:
        STEP_CONTEXT1: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT1"
      shell: bash
    - name: step 3
      id: random-generator
      env:
        STEP_CONTEXT2: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT2"
      shell: bash

      
    # - id: random-number-generator
    #   run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    #   shell: bash
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash
    # - run: goodbye.sh
    #   shell: bash
