on:
  push:
  issues:
    types: [opened]
  release:
    types: [created]
jobs:
  test:
  uses:  okimaureen/test/.github/workflows/reuse.yml@main
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test' > 'README.md'
  
     
