on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  # push:
  #  branches: "*"

concurrency:

  group: ${{ github.workflow }}-${{ github.head_ref }} || ${{ github.run_id }}

  cancel-in-progress: true
  
jobs:
 test:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 1m
          
      - name: Set the value in bash
        id: step_one
        run: |

            echo  ${{ github.workflow }}-${{ github.head_ref }} || ${{ github.run_id }}

            delimiter="$(openssl rand -hex 8)"
            echo "output-name<<${delimiter}" >> "${GITHUB_OUTPUT}"
            echo "KEYCLOAK_LOCALE=; KC_RESTART=;" >> "${GITHUB_OUTPUT}"
            echo "${delimiter}" >> "${GITHUB_OUTPUT}"
  

      - name: Get value
        env:
          cookies: ${{ steps.step_one.outputs.output-name }}
        run: echo "This is the value of $cookies"


     
  
