on:
  workflow_dispatch:
  push:
   branches: "*"
  
jobs:
 test:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    steps:
    - uses: okimaureen/zola-deploy-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
     
