on:
  workflow_dispatch:
  push:
   branches: "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} || ${{ github.run_id }}
  cancel-in-progress: true
  
jobs:
 test:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value in bash
        id: step_one
        run: |
  
            delimiter="$(openssl rand -hex 8)"
            echo "output-name<<${delimiter}" >> "${GITHUB_OUTPUT}"
            echo "KEYCLOAK_LOCALE=; KC_RESTART=;" >> "${GITHUB_OUTPUT}"
            echo "${delimiter}" >> "${GITHUB_OUTPUT}"
  

      - name: Get value
        env:
          cookies: ${{ steps.step_one.outputs.output-name }}
        run: echo "This is the value of $cookies"


     
  
