on:
  workflow_dispatch:
  push:
   branches: "*"
  
jobs:
 test:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    steps:
      - name: Set the value in bash
        id: step_one
        run: |
          {
            echo 'cookies<<EOF'
            KEYCLOAK_LOCALE=; KC_RESTART=;
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Get value
        env:
          cookies: ${{ steps.step_one.outputs.cookies }}
        run: echo "This is the value of $cookies"


     
  
