on:
  issues:
  issue_comment:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'test' > 'README.md'
      - uses: mheap/phpunit-matcher-action@master
        with:
          branch: auto-merge
          commit-message: 'Update README.md'
          title: 'Updating README.md'
          body: 'Closes #${{github.event.issue.number}}'
