name: bool

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run debug session'
        required: false
        type: boolean


jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Start debug session
      run: |
       echo "Debug session starting ..."
       echo "debug_enabled: ${{github.workspace}}/actions"
      env:
          DEBUG_ENABLED: ${{ inputs.debug_enabled }}
    - name: added step
      run: |
       echo "added stepDebug session starting ..."
    - name: added new step
      run: |
       echo "added stepDebug session starting ..."
  
