name: caller
on:
  workflow_dispatch:

jobs:
  set_job_name:
    runs-on: ubuntu-latest
    outputs:
      deploy_prefix: ${{ steps.set-job.outputs.job_name }}
    steps:
      - name: set output for deploy_prefix
        id: set-job
        run: |
          echo "job_name=${{ github.job }}" >> $GITHUB_OUTPUT


  caller_job:
    uses: ./.github/workflows/called1.yml
    with:
      workflow_name: ${{needs.set_job_name.outputs.job_name }}




