name: called
on:
  workflow_call:
    inputs:
      job_name:
        required: true
        type: string


jobs:
  called_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo job name:${{ inputs.job_name }}
