name: called
on:
  workflow_call:
    inputs:
      workflow_name:
        required: true
        type: string


jobs:
  called_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.workflow_name }}"
