name: caller
on:
  workflow_dispatch:


jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - name: Set Job Name
      #   id: set_job_name
      #   run: echo "::set-output name=job_name::${{ job.name }}"

      - name: Call Reusable Workflow
        uses: ./.github/workflows/called1.yml
        with:
          workflow_name: ${{github.job  }}

# jobs:
#   caller_job:
#     uses: ./.github/workflows/called1.yml
#     with:
#       workflow_name: ${{github.job }}

#   job2:
#     runs-on: ubuntu-latest
#     needs: caller_job
#     steps:
#       - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
  
  

