name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Using the current repo to perform coverage analysis
      - uses: joshmfrankel/simplecov-check-action@main
        with:
          minimum_coverage: 90
          github_token: ${{ secrets.GITHUB_TOKEN }}
