name: ff-test -> master

on: push
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Merge fg-test->master ff_only
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "test"
          git config user.email "test@test.com"
          git fetch origin master
          git fetch origin fg-test
          git checkout master
          git pull --rebase
          git merge fg-test --ff-only --allow-unrelated-histories
          git push origin master
