name: Tests

on:
  push:
    branches:
      - main
  pull_request_target:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled]
jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Using the current repo to perform coverage analysis
      - uses: joshmfrankel/simplecov-check-action@main
        with:
          minimum_coverage: 90
          github_token: ${{ secrets.GITHUB_TOKEN }}
