name: fm-test -> master

on: push
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Merge fm-test->master ff_only
        env:
          GITHUB_TOKEN: ${{ secrets.CODE_SECRET }}
          NOTMASKEd: hello
        run: |
          echo "${ GITHUB_TOKEN }"
          echo "${ NOTMASKEd }"
          df -h
          git config user.name "test"
          git config user.email "test@test.com"
          git fetch origin master
          git fetch origin fm-test
          git checkout master
          git pull --rebase
          git merge fm-test --ff-only --allow-unrelated-histories
          git push origin master
    
      - name: run
        id: run
        uses: Codesee-io/codesee-map-action@latest
        with:
          api_token: ${{ secrets.CODESEE_ARCH_DIAG_API_TOKEN }}
          github_ref: ${{ github.ref }}
          support_typescript: true
