name: Clone and Push Branch

on:
  push:
    branches:
      - main

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone branch
        run: |
          git push https://github.com/todoproject HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
