name: Job Conditionals

on: workflow_dispatch

jobs:
  a:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
  
  b:
   needs: a
   if: failure()
   runs-on: ubuntu-latest

   steps:
    - run: echo "Hello world"
    
  c:
   needs: b
   if: needs.b.result == 'success'
   runs-on: ubuntu-latest

   steps:
    - run: echo "Hello world"
