name: Job Conditionals

on: workflow_dispatch

jobs:
  a:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
  
  b:
   needs: a
   if: always()
   runs-on: ubuntu-latest

   steps:
    - run: echo "Hello world"
