name: Job Conditionals

on:
  pull_request:
  workflow_dispatch:

jobs:
  a:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'okimaureen'

    steps:
      - run: |
              echo "Hello world"
              echo "refs/pull/${{ github.event.number }}/merge"
  
  b:
   needs: a
   runs-on: ubuntu-latest

   steps:
    - run: exit 1
    
  c:
   needs: b
   if: |
    always() && needs.b.result == 'success'
   runs-on: ubuntu-latest

   steps:
    - run: echo "Hello world"
