name: test deployment

on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.webapp-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Pre deploy
        run: |
          echo "PRE DEPLOY"
      - name: Deploy
        id: deploy
        run: |
          echo "DEPLOY"
          echo "::set-output name=webapp-url::https://github.com"
      - name: Post deploy
        run: echo Hello, world!
