name: test deployment two

on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: ${{ github.token  }}
          environment: staging
          target_url: https://github.com
          ref: ${{ github.event.pull_request.head.sha }}
