name: Manually triggered workflow (manual)
on:
   workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo "name: ${{ github.event.inputs.name }}" 
       
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path:  ${{ github.workspace }}
        
    - name: Archive development artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path:  ${{ github.workspace }}
