name: Manually triggered workflow (manual)
on:
   workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse' 
      environment:
        description: 'env'
        required: true
        default: 'stage'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo "name: ${{ github.event.inputs.name }}" 
       
    - name: Archive production artifacts
      id: tf_apply
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
      with:
        name: my-artifact
        path:  ${{ github.workspace }}
        
    - name: Archive development artifacts
      id: tf_applys
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
      with:
        name: my-artifact
        path:  ${{ github.workspace }}
