name: Testing

on:
 push:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        run: |
          echo "action_state=red" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
           echo "${{ env.action_state }}"
