name: Reusable workflow

on:
  workflow_call:
    inputs:
      node_version:
        description: 'version'
        required: true
        type: string
      os:
        description: 'operating system'
        required: true
        type: string
     
jobs:
  build_stack:
    runs-on: ${{ inputs.os}}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
