name: Reusable workflow

on:
  workflow_call:
    inputs:
      node_version:
        description: 'version'
        required: true
        type: string
     
jobs:
  build_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
