name: Test bug
on:
  workflow_dispatch:
jobs:
  test_bug:
    runs-on: ubuntu-latest
    steps:
      - id: testing
        run: echo "::set-output name=result::result"
      - id: calc_results
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: core.setOutput('result', 'result');
      - id: debug
        run: echo  "${{ steps.calc_results.outputs.results }}"
      - id: resul
        run: echo  "${{ steps.testing.outputs.result }}"
