name: Reusable workflow example

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo "This is a noop job to satisfy pull-request requirements if the ci-pulumi workflow doesn't runs"
