name: release

on: push
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: testing
        env:
          GITHUB_TOKEN: ${{ secrets.CODE_SECRET }}
          NOTMASKEd: hello
        run: |
          echo "${ GITHUB_TOKEN }"
          echo "${ NOTMASKEd }"
    
      - name: create release
        id: run
        uses:  actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}.${{ github.run_id }}
          release_name: Release ${{ github.run_id }} - ${{ github.ref }}
          draft: false
          prerelease: false
