on:
  push:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/repo_action.yml'
    types: [opened, synchronize, closed]
  workflow_dispatch:
    
jobs:
  hola_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#       - name: removelabel
#         uses: buildsville/add-remove-label@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           label: 'review-app'
#           type: remove
      - name: Run local rituals
        if: ${{ success() }}
        uses: github.com/okimaureen/test@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
