test_runner_context:name: PostgreSQL service example
on: push
jobs:
  # Label of the container job
  container-job:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PORT: 5432
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          -v ${{ runner.temp }}/pgdata:/var/lib/postgresql/data
  
