name: demo

on:
  pull_request:
  paths-ignore:
  - 'new/**'
jobs:
  important_check:
    runs-on: ubuntu-latest
    steps:
    - name: Start debug session
      run: |
       echo "Debug session starting ..."
 
