name: startup_failure
on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Intentional Startup Failure
        run: |
          echo "This step intentionally fails during startup."
          error "Startup failure"
      
      - name: This step will not be executed if the previous step fails
        run: echo "This step will not run if the previous step fails"
