# This is a basic workflow to help you get started with Actions

name: CI-reuse

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-workflow:
    uses: Cincinnati-Insurance/WSHQ-Webportals-Solutions-SelfServe/.github/workflows/receive.yml@main
