name: GitHub simple example

on:
 push:


env:
   env_var: ${{ vars.TT }}

jobs:
  run_smoke_tests:
    environment: stage

    runs-on: ubuntu-20.04


    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print Environment Variables
        run: |
          echo "variable from shell environment : $env_var"
          echo "TT: ${{ vars.TT }}"
