name: WorkflowB
on: [push]
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 1m
  required-for-merge:
    name: "ptest"
    runs-on: ubuntu-latest
    needs:   foo  
    steps:
      - name: Fail
        run: echo "Hello world"
        env:
          DAY_OF_WEEK: "hellonmm"

      - name: Install packages
        run: |
         echo "${{ env.DAY_OF_WEEK }}"
